-- MySQL Script generated by MySQL Workbench
-- 02/01/18 22:04:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pondodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pondodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pondodb` DEFAULT CHARACTER SET utf8 ;
USE `pondodb` ;

-- -----------------------------------------------------
-- Table `pondodb`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pondodb`.`USER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email_address` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pondodb`.`INVESTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pondodb`.`INVESTOR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gender` CHAR(1) NOT NULL,
  `civil_status` VARCHAR(25) NOT NULL,
  `birthdate` DATETIME NOT NULL,
  `document` BLOB NOT NULL,
  `USER_id` INT NOT NULL,
  PRIMARY KEY (`id`, `USER_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_INVESTOR_USER_idx` (`USER_id` ASC),
  CONSTRAINT `fk_INVESTOR_USER`
    FOREIGN KEY (`USER_id`)
    REFERENCES `pondodb`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pondodb`.`BUSINESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pondodb`.`BUSINESS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `nature` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `dti_permit_number` VARCHAR(45) NOT NULL,
  `document` BLOB NOT NULL,
  `USER_id` INT NOT NULL,
  PRIMARY KEY (`id`, `USER_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_BUSINESS_USER1_idx` (`USER_id` ASC),
  CONSTRAINT `fk_BUSINESS_USER1`
    FOREIGN KEY (`USER_id`)
    REFERENCES `pondodb`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
